# Imputación por K-Nearest-Neighbor

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [7]:
%cd "/Tu ruta de / trabajo/"
print('\nArchivos dentro de la carpera:\n')
%ls

/content/drive/My Drive/C5/Trabajos C5/IMPUTACION DE DATOS/kNN

Archivos dentro de la carpera:

base_SIN_IMPUTAR.csv  imputacion_kNN

In [9]:
df = pd.read_csv("base_SIN_IMPUTAR.csv", encoding='iso8859-1')

In [11]:
df.head()

,fid,CVEGEO,CVE_ENT,CVE_MUN,CVE_LOC,CVE_AGEB,CVE_MZA,AMBITO,TIPOMZA,POBTOT,...,Derrame._3,Disturbio.,Disturbi_1,Disturbi_2,Disturbi_3,Servicios.,Servicio_1,Servicio_2,TM.INTOXIC,DESORDEN_S
0,19108,0901700010403001,9,17,1,403.0,1,Urbana,Típica,0,...,0,0,3,5,4,0,0,0,0,22
1,19109,0901700010390021,9,17,1,390.0,21,Urbana,Típica,679,...,0,1,2,0,2,0,0,0,0,12
2,19110,0901700010390013,9,17,1,390.0,13,Urbana,Típica,461,...,0,0,0,3,1,0,0,2,0,7
3,19111,0901700010390012,9,17,1,390.0,12,Urbana,Típica,128,...,0,0,0,0,0,0,0,0,0,0
4,19112,0901700010390010,9,17,1,390.0,10,Urbana,Contenedora,4,...,0,0,9,3,4,0,0,0,0,50

In [67]:
datos = df.iloc[:,[0]+list(range(9, 230))] ; datos.head(10)

,fid,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_3YMAS,P_3YMAS_F,P_3YMAS_M,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
0,19108,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19109,679,359.0,320.0,27.0,14.0,13.0,652.0,345.0,307.0,...,122.0,180.0,149.0,78.0,61.0,38.0,6.0,6.0,35.0,NaN
2,19110,461,237.0,224.0,25.0,17.0,8.0,436.0,220.0,216.0,...,87.0,125.0,104.0,55.0,31.0,28.0,NaN,9.0,29.0,NaN
3,19111,128,62.0,66.0,3.0,3.0,0.0,125.0,59.0,66.0,...,24.0,34.0,28.0,12.0,8.0,9.0,0.0,NaN,9.0,0.0
4,19112,4,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,19113,65,32.0,33.0,NaN,NaN,NaN,63.0,31.0,32.0,...,11.0,20.0,11.0,5.0,5.0,4.0,0.0,NaN,8.0,0.0
6,19114,92,56.0,36.0,3.0,NaN,NaN,89.0,54.0,35.0,...,21.0,25.0,20.0,7.0,11.0,6.0,0.0,0.0,9.0,0.0
7,19119,222,122.0,100.0,12.0,5.0,7.0,210.0,117.0,93.0,...,42.0,55.0,39.0,18.0,6.0,8.0,NaN,0.0,21.0,0.0
8,19126,75,38.0,37.0,3.0,NaN,NaN,72.0,37.0,35.0,...,10.0,23.0,13.0,NaN,7.0,6.0,NaN,NaN,7.0,NaN
9,19127,913,465.0,448.0,32.0,16.0,16.0,881.0,449.0,432.0,...,175.0,253.0,202.0,86.0,79.0,61.0,NaN,3.0,58.0,NaN

In [37]:
from sklearn.impute import KNNImputer

In [68]:
imputer = KNNImputer(n_neighbors=6, weights="distance")
imputados_uni = imputer.fit_transform(datos)
datos_imputados = pd.DataFrame(imputados_uni)
#np.stack((imputados_uni, imputados_dis), axis=1)

In [69]:
datos_imputados.head(50)

,0,1,2,3,4,5,6,7,8,9,...,212,213,214,215,216,217,218,219,220,221
0,19108.0,0.0,11.068642,10.915592,2.962142,1.402328,1.127390,69.344776,34.962657,34.382118,...,12.305388,19.797862,13.069155,5.762816,6.645453,5.245278,0.000000,1.024380,7.557928,0.0
1,19109.0,679.0,359.000000,320.000000,27.000000,14.000000,13.000000,652.000000,345.000000,307.000000,...,122.000000,180.000000,149.000000,78.000000,61.000000,38.000000,6.000000,6.000000,35.000000,0.0
2,19110.0,461.0,237.000000,224.000000,25.000000,17.000000,8.000000,436.000000,220.000000,216.000000,...,87.000000,125.000000,104.000000,55.000000,31.000000,28.000000,2.386560,9.000000,29.000000,0.0
3,19111.0,128.0,62.000000,66.000000,3.000000,3.000000,0.000000,125.000000,59.000000,66.000000,...,24.000000,34.000000,28.000000,12.000000,8.000000,9.000000,0.000000,2.667974,9.000000,0.0
4,19112.0,4.0,2.000000,2.000000,2.925800,1.323076,1.018579,67.642597,33.905393,33.737204,...,11.911195,19.184567,12.618268,6.041140,6.501903,4.811289,0.000000,1.045611,7.468242,0.0
5,19113.0,65.0,32.000000,33.000000,3.455199,1.503546,0.732379,63.000000,31.000000,32.000000,...,11.000000,20.000000,11.000000,5.000000,5.000000,4.000000,0.000000,1.238806,8.000000,0.0
6,19114.0,92.0,56.000000,36.000000,3.000000,1.698323,0.930490,89.000000,54.000000,35.000000,...,21.000000,25.000000,20.000000,7.000000,11.000000,6.000000,0.000000,0.000000,9.000000,0.0
7,19119.0,222.0,122.000000,100.000000,12.000000,5.000000,7.000000,210.000000,117.000000,93.000000,...,42.000000,55.000000,39.000000,18.000000,6.000000,8.000000,0.626695,0.000000,21.000000,0.0
8,19126.0,75.0,38.000000,37.000000,3.000000,1.585079,0.781821,72.000000,37.000000,35.000000,...,10.000000,23.000000,13.000000,5.533830,7.000000,6.000000,0.000000,1.182513,7.000000,0.0
9,19127.0,913.0,465.000000,448.000000,32.000000,16.000000,16.000000,881.000000,449.000000,432.000000,...,175.000000,253.000000,202.000000,86.000000,79.000000,61.000000,4.515164,3.000000,58.000000,0.0
10,19146.0,434.0,239.000000,195.000000,19.000000,7.000000,12.000000,415.000000,232.000000,183.000000,...,70.000000,109.000000,80.000000,48.000000,32.000000,14.000000,3.000000,3.000000,29.000000,0.0
11,19150.0,4.0,21.442127,21.657903,2.628538,1.160714,0.869540,56.706788,28.531359,28.175428,...,9.842713,16.116777,10.286460,5.103682,5.926117,4.362185,0.000000,1.067297,6.707515,0.0
12,19157.0,37.0,14.000000,23.000000,0.000000,0.000000,0.000000,37.000000,14.000000,23.000000,...,6.000000,9.000000,6.000000,4.000000,4.645329,3.770713,0.000000,0.876846,5.000000,0.0
13,19253.0,69.0,39.000000,30.000000,9.000000,7.000000,0.392635,60.000000,32.000000,28.000000,...,7.000000,14.000000,6.000000,3.000000,4.546085,0.000000,0.000000,0.953019,10.000000,0.0
14,19254.0,174.0,89.000000,85.000000,4.000000,3.159578,3.418823,170.000000,87.000000,83.000000,...,23.000000,34.000000,28.000000,11.000000,9.000000,4.000000,3.000000,3.654776,10.000000,0.0
15,19255.0,205.0,112.000000,93.000000,6.000000,4.000000,4.929625,199.000000,108.000000,91.000000,...,28.000000,49.000000,38.000000,7.000000,5.000000,7.058353,0.732664,9.000000,21.000000,0.0
16,19267.0,75.0,43.000000,32.000000,4.108138,0.955403,0.000000,73.000000,41.000000,32.000000,...,11.000000,17.000000,11.000000,5.000000,4.000000,3.665746,0.000000,0.000000,7.000000,0.0
17,19268.0,54.0,29.000000,25.000000,4.133203,0.000000,0.602569,53.000000,29.000000,24.000000,...,16.000000,22.000000,12.000000,5.000000,4.000000,6.000000,0.000000,0.722596,9.000000,0.0
18,19269.0,119.0,57.000000,62.000000,4.227999,0.000000,2.013592,118.000000,57.000000,61.000000,...,29.000000,39.000000,30.000000,17.000000,8.000000,6.000000,0.000000,2.425561,10.000000,0.0
19,19270.0,50.0,27.000000,23.000000,4.081673,0.000000,0.236088,48.000000,27.000000,21.000000,...,10.000000,15.000000,12.000000,9.000000,3.000000,3.000000,0.000000,0.328629,4.000000,0.0
20,19271.0,69.0,34.000000,35.000000,4.140364,0.000000,0.678303,68.000000,34.000000,34.000000,...,17.000000,19.000000,17.000000,8.000000,5.000000,3.000000,0.000000,0.776518,6.775818,0.0
21,19272.0,151.0,89.000000,62.000000,6.000000,5.000000,3.388141,145.000000,84.000000,61.000000,...,30.000000,35.000000,29.000000,19.000000,12.000000,9.000000,0.000000,4.000000,12.000000,0.0
22,19273.0,139.0,80.000000,59.000000,5.000000,2.669385,4.000000,134.000000,79.000000,55.000000,...,17.000000,27.000000,20.000000,9.000000,4.000000,7.000000,0.000000,4.000000,13.000000,0.0
23,19284.0,340.0,169.000000,171.000000,11.000000,6.000000,5.000000,329.000000,163.000000,166.000000,...,71.000000,93.000000,71.000000,54.000000,32.000000,17.000000,1.408941,5.426585,28.000000,0.0
24,19285.0,47.0,25.000000,22.000000,4.018851,0.827510,0.000000,46.000000,24.000000,22.000000,...,8.000000,12.000000,7.000000,6.439805,4.103945,3.602965,0.000000,0.000000,4.000000,0.0
25,19292.0,299.0,158.000000,141.000000,17.000000,9.000000,8.000000,282.000000,149.000000,133.000000,...,54.000000,77.000000,55.000000,18.000000,24.000000,14.000000,1.425959,4.361304,20.000000,0.0
26,19293.0,2.0,31.607071,27.005563,4.947414,1.071209,0.735228,56.310568,30.247679,26.062889,...,11.378483,16.251028,10.728380,7.312528,4.365892,3.885502,0.000000,1.276081,6.673981,0.0
27,19294.0,417.0,244.000000,173.000000,14.000000,4.000000,10.000000,403.000000,240.000000,163.000000,...,67.000000,99.000000,79.000000,23.000000,20.000000,19.000000,0.000000,6.000000,28.000000,0.0
28,19323.0,927.0,477.000000,450.000000,36.000000,19.000000,17.000000,891.000000,458.000000,433.000000,...,198.000000,261.000000,188.000000,126.000000,66.000000,52.000000,4.000000,15.000000,89.000000,0.0
29,19487.0,80.0,35.000000,45.000000,3.000000,0.000000,3.000000,77.000000,35.000000,42.000000,...,3.000000,9.000000,5.000000,7.950662,0.000000,5.080711,0.000000,4.000000,8.000000,0.0
30,19488.0,297.0,148.000000,149.000000,12.000000,8.000000,4.000000,285.000000,140.000000,145.000000,...,45.000000,74.000000,54.000000,35.000000,7.000000,3.000000,1.018677,4.058652,24.000000,0.0
31,19503.0,32.0,17.000000,15.000000,3.017362,0.963524,0.000000,31.000000,16.000000,15.000000,...,6.000000,9.000000,6.000000,3.000000,3.000000,5.635450,0.000000,0.000000,3.000000,0.0
32,19504.0,5.0,29.757033,29.448954,3.944619,0.408027,1.228653,57.441169,28.876247,28.564922,...,8.155528,14.407776,10.448290,6.496688,4.350890,6.243627,0.000000,1.289049,5.882988,0.0
33,19590.0,67.0,36.000000,31.000000,3.292876,0.390206,0.000000,66.000000,35.000000,31.000000,...,13.000000,23.000000,22.000000,13.000000,9.000000,7.000000,0.000000,0.000000,8.013142,0.0
34,19662.0,140.0,74.000000,66.000000,8.000000,2.089051,7.000000,132.000000,73.000000,59.000000,...,20.000000,25.000000,21.000000,11.000000,8.000000,6.000000,0.000000,3.005748,5.000000,0.0
35,19663.0,141.0,71.000000,70.000000,6.000000,1.196488,5.000000,135.000000,70.000000,65.000000,...,24.000000,34.000000,28.000000,13.000000,7.000000,8.000000,0.000000,2.967726,7.000000,0.0
36,19664.0,102.0,44.000000,58.000000,4.000000,0.723520,3.000000,98.000000,43.000000,55.000000,...,14.000000,29.000000,19.000000,6.000000,5.000000,3.000000,0.319648,0.000000,10.000000,0.0
37,19665.0,60.0,30.000000,30.000000,0.000000,0.000000,0.000000,60.000000,30.000000,30.000000,...,15.000000,20.000000,15.000000,10.000000,11.000000,7.000000,0.000000,3.000000,8.000000,0.0
38,19666.0,161.0,75.000000,86.000000,7.000000,2.770380,5.000000,154.000000,73.000000,81.000000,...,26.000000,43.000000,35.000000,20.000000,19.000000,9.000000,0.340951,2.964426,7.000000,0.0
39,19667.0,130.0,76.000000,54.000000,5.000000,3.000000,4.316687,125.000000,73.000000,52.000000,...,12.000000,26.000000,18.000000,10.000000,7.000000,6.000000,0.298745,5.000000,14.000000,0.0
40,19668.0,8.0,44.317868,42.617916,4.071947,0.586883,2.605771,84.200281,43.335029,40.865252,...,14.278667,22.994055,17.718999,9.327054,8.365558,6.104525,0.000000,1.982960,8.304136,0.0
41,19669.0,0.0,44.178636,42.512216,4.046019,0.587232,2.580161,83.983951,43.199353,40.784598,...,14.262792,22.995978,17.713607,9.331599,8.373400,6.102951,0.000000,1.982483,8.323934,0.0
42,19757.0,62.0,29.000000,33.000000,1.608758,0.390270,0.459355,60.000000,28.000000,32.000000,...,12.000000,18.000000,14.000000,6.000000,8.000000,7.000000,0.000000,1.231768,6.000000,0.0
43,19944.0,120.0,73.000000,47.000000,7.000000,0.818029,5.000000,113.000000,71.000000,42.000000,...,12.000000,25.000000,15.000000,7.000000,8.000000,3.000000,3.000000,4.000000,17.000000,0.0
44,19945.0,18.0,11.000000,7.000000,2.142965,0.557534,0.000000,16.000000,9.000000,7.000000,...,10.874956,4.000000,10.270785,4.474923,0.000000,1.986962,0.000000,0.000000,6.640071,0.0
45,19946.0,54.0,29.000000,25.000000,4.000000,0.521990,0.265779,50.000000,27.000000,23.000000,...,8.000000,13.000000,6.000000,0.000000,3.000000,3.000000,0.000000,0.000000,8.000000,0.0
46,19947.0,58.0,32.000000,26.000000,0.000000,0.000000,0.000000,58.000000,32.000000,26.000000,...,13.000000,16.000000,9.000000,4.000000,3.000000,3.906136,0.000000,0.000000,9.000000,0.0
47,19948.0,211.0,98.000000,113.000000,21.000000,8.000000,13.000000,190.000000,90.000000,100.000000,...,5.000000,33.000000,10.000000,14.752834,0.000000,0.000000,0.502028,5.000000,27.000000,0.0
48,19970.0,87.0,52.000000,35.000000,0.000000,0.000000,0.000000,87.000000,52.000000,35.000000,...,18.000000,21.000000,16.000000,7.000000,9.000000,3.000000,0.381868,1.034785,8.000000,0.0
49,19971.0,12.0,7.000000,5.000000,1.934045,0.573412,0.000000,10.000000,6.000000,4.000000,...,10.894992,3.000000,10.331865,3.000000,2.040902,0.000000,0.000000,0.000000,6.598142,0.0

In [70]:
datos_imputados.to_csv('datos_imputados.csv', index=False)